server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}}
spring.data.mongodb.database=${MONGO_DATABASE:${env.MONGO_DATABASE}}
